puts "Digite uma frase: "
phrase = gets.chomp.split('')
phrase_up = []
index = 0

phrase.each do |char|
	case char
	when 'a'
		phrase_up[index] = 'A'
	when 'á'
		phrase_up[index] = 'Á'
	when 'ã'
		phrase_up[index] = 'Ã'
	when 'â'
		phrase_up[index] = 'Â'
	when 'à'
		phrase_up[index] = 'À'
	when 'b'
		phrase_up[index] = 'B'
	when 'c'
		phrase_up[index] = 'C'
	when 'd'
		phrase_up[index] = 'D'
	when 'e'
		phrase_up[index] = 'E'
	when 'é'
		phrase_up[index] = 'É'
	when 'ê'
		phrase_up[index] = 'Ê'
	when 'è'
		phrase_up[index] = 'È'
	when 'f'
		phrase_up[index] = 'F'
	when 'g'
		phrase_up[index] = 'G'
	when 'h'
		phrase_up[index] = 'H'
	when 'i'
		phrase_up[index] = 'I'
	when 'í'
		phrase_up[index] = 'Í'
	when 'î'
		phrase_up[index] = 'Î'
	when 'ì'
		phrase_up[index] = 'Ì'
	when 'j'
		phrase_up[index] = 'J'
	when 'k'
		phrase_up[index] = 'K'
	when 'l'
		phrase_up[index] = 'L'
	when 'm'
		phrase_up[index] = 'M'
	when 'n'
		phrase_up[index] = 'N'
	when 'o'
		phrase_up[index] = 'O'
	when 'ó'
		phrase_up[index] = 'Ó'
	when 'ô'
		phrase_up[index] = 'Ô'
	when 'õ'
		phrase_up[index] = 'Õ'
	when 'ò'
		phrase_up[index] = 'Ò'
	when 'p'
		phrase_up[index] = 'P'
	when 'q'
		phrase_up[index] = 'Q'
	when 'r'
		phrase_up[index] = 'R'
	when 's'
		phrase_up[index] = 'S'
	when 't'
		phrase_up[index] = 'T'
	when 'u'
		phrase_up[index] = 'U'
	when 'ú'
		phrase_up[index] = 'Ú'
	when 'û'
		phrase_up[index] = 'Û'
	when 'ù'
		phrase_up[index] = 'Ù'
	when 'v'
		phrase_up[index] = 'V'
	when 'w'
		phrase_up[index] = 'W'
	when 'x'
		phrase_up[index] = 'X'
	when 'y'
		phrase_up[index] = 'Y'
	when 'z'
		phrase_up[index] = 'Z'
	when 'A'
		phrase_up[index] = 'A'
	when 'Á'
		phrase_up[index] = 'Á'
	when 'Ã'
		phrase_up[index] = 'Ã'
	when 'Â'
		phrase_up[index] = 'Â'
	when 'À'
		phrase_up[index] = 'À'
	when 'B'
		phrase_up[index] = 'B'
	when 'C'
		phrase_up[index] = 'C'
	when 'D'
		phrase_up[index] = 'D'
	when 'E'
		phrase_up[index] = 'E'
	when 'É'
		phrase_up[index] = 'É'
	when 'Ê'
		phrase_up[index] = 'Ê'
	when 'È'
		phrase_up[index] = 'È'
	when 'F'
		phrase_up[index] = 'F'
	when 'G'
		phrase_up[index] = 'G'
	when 'H'
		phrase_up[index] = 'H'
	when 'I'
		phrase_up[index] = 'I'
	when 'Í'
		phrase_up[index] = 'Í'
	when 'Î'
		phrase_up[index] = 'Î'
	when 'Ì'
		phrase_up[index] = 'Ì'
	when 'J'
		phrase_up[index] = 'J'
	when 'K'
		phrase_up[index] = 'K'
	when 'L'
		phrase_up[index] = 'L'
	when 'M'
		phrase_up[index] = 'M'
	when 'N'
		phrase_up[index] = 'N'
	when 'O'
		phrase_up[index] = 'O'
	when 'Ó'
		phrase_up[index] = 'Ó'
	when 'Ô'
		phrase_up[index] = 'Ô'
	when 'Õ'
		phrase_up[index] = 'Õ'
	when 'Ò'
		phrase_up[index] = 'Ò'
	when 'P'
		phrase_up[index] = 'P'
	when 'Q'
		phrase_up[index] = 'Q'
	when 'R'
		phrase_up[index] = 'R'
	when 'S'
		phrase_up[index] = 'S'
	when 'T'
		phrase_up[index] = 'T'
	when 'U'
		phrase_up[index] = 'U'
	when 'Ú'
		phrase_up[index] = 'Ú'
	when 'Û'
		phrase_up[index] = 'Û'
	when 'Ù'
		phrase_up[index] = 'Ù'
	when 'V'
		phrase_up[index] = 'V'
	when 'W'
		phrase_up[index] = 'W'
	when 'X'
		phrase_up[index] = 'X'
	when 'Y'
		phrase_up[index] = 'Y'
	when 'Z'
		phrase_up[index] = 'Z'
	when ' '
		phrase_up[index] = ' '
	end
	index += 1 
end

puts "#{phrase_up.join}"