puts "Digite uma frase: "
phrase = gets.chomp.split('')
phrase_up = []

phrase.each_with_index do |char, index|
	case char
	when 'A'
		phrase_up[index] = 'A'
	when 'Á'
		phrase_up[index] = 'á'
	when 'Ã'
		phrase_up[index] = 'ã'
	when 'Â'
		phrase_up[index] = 'â'
	when 'À'
		phrase_up[index] = 'à'
	when 'B'
		phrase_up[index] = 'b'
	when 'C'
		phrase_up[index] = 'c'
	when 'D'
		phrase_up[index] = 'd'
	when 'E'
		phrase_up[index] = 'e'
	when 'É'
		phrase_up[index] = 'é'
	when 'Ê'
		phrase_up[index] = 'ê'
	when 'È'
		phrase_up[index] = 'è'
	when 'F'
		phrase_up[index] = 'f'
	when 'G'
		phrase_up[index] = 'g'
	when 'H'
		phrase_up[index] = 'h'
	when 'I'
		phrase_up[index] = 'i'
	when 'Í'
		phrase_up[index] = 'í'
	when 'Î'
		phrase_up[index] = 'î'
	when 'Ì'
		phrase_up[index] = 'ì'
	when 'J'
		phrase_up[index] = 'j'
	when 'K'
		phrase_up[index] = 'k'
	when 'L'
		phrase_up[index] = 'l'
	when 'M'
		phrase_up[index] = 'm'
	when 'N'
		phrase_up[index] = 'n'
	when 'O'
		phrase_up[index] = 'o'
	when 'Ó'
		phrase_up[index] = 'ó'
	when 'Ô'
		phrase_up[index] = 'ô'
	when 'Õ'
		phrase_up[index] = 'õ'
	when 'Ò'
		phrase_up[index] = 'ò'
	when 'P'
		phrase_up[index] = 'p'
	when 'Q'
		phrase_up[index] = 'q'
	when 'R'
		phrase_up[index] = 'r'
	when 'S'
		phrase_up[index] = 's'
	when 'T'
		phrase_up[index] = 't'
	when 'U'
		phrase_up[index] = 'u'
	when 'Ú'
		phrase_up[index] = 'ú'
	when 'Û'
		phrase_up[index] = 'û'
	when 'Ù'
		phrase_up[index] = 'ù'
	when 'V'
		phrase_up[index] = 'v'
	when 'W'
		phrase_up[index] = 'w'
	when 'X'
		phrase_up[index] = 'x'
	when 'Y'
		phrase_up[index] = 'y'
	when 'Z'
		phrase_up[index] = 'z'
	when ' '
		phrase_up[index] = ' '
	end
end

puts "#{phrase_up.join}"