puts "Digite uma frase: "
phrase = gets.chomp.split('')
phrase_up = []
index = 0

phrase.each do |char|
	case char
	when 'A'
		phrase_up[index] = 'a'
	when 'Á'
		phrase_up[index] = 'á'
	when 'Ã'
		phrase_up[index] = 'ã'
	when 'Â'
		phrase_up[index] = 'â'
	when 'À'
		phrase_up[index] = 'à'
	when 'B'
		phrase_up[index] = 'b'
	when 'C'
		phrase_up[index] = 'c'
	when 'D'
		phrase_up[index] = 'd'
	when 'E'
		phrase_up[index] = 'e'
	when 'É'
		phrase_up[index] = 'é'
	when 'Ê'
		phrase_up[index] = 'ê'
	when 'È'
		phrase_up[index] = 'è'
	when 'F'
		phrase_up[index] = 'f'
	when 'G'
		phrase_up[index] = 'g'
	when 'H'
		phrase_up[index] = 'h'
	when 'I'
		phrase_up[index] = 'i'
	when 'Í'
		phrase_up[index] = 'í'
	when 'Î'
		phrase_up[index] = 'î'
	when 'Ì'
		phrase_up[index] = 'ì'
	when 'J'
		phrase_up[index] = 'j'
	when 'K'
		phrase_up[index] = 'k'
	when 'L'
		phrase_up[index] = 'l'
	when 'M'
		phrase_up[index] = 'm'
	when 'N'
		phrase_up[index] = 'n'
	when 'O'
		phrase_up[index] = 'o'
	when 'Ó'
		phrase_up[index] = 'ó'
	when 'Ô'
		phrase_up[index] = 'ô'
	when 'Õ'
		phrase_up[index] = 'õ'
	when 'Ò'
		phrase_up[index] = 'ò'
	when 'P'
		phrase_up[index] = 'p'
	when 'Q'
		phrase_up[index] = 'q'
	when 'R'
		phrase_up[index] = 'r'
	when 'S'
		phrase_up[index] = 's'
	when 'T'
		phrase_up[index] = 't'
	when 'U'
		phrase_up[index] = 'u'
	when 'Ú'
		phrase_up[index] = 'ú'
	when 'Û'
		phrase_up[index] = 'û'
	when 'Ù'
		phrase_up[index] = 'ù'
	when 'V'
		phrase_up[index] = 'v'
	when 'W'
		phrase_up[index] = 'w'
	when 'X'
		phrase_up[index] = 'x'
	when 'Y'
		phrase_up[index] = 'y'
	when 'Z'
		phrase_up[index] = 'z'
	when 'a'
		phrase_up[index] = 'a'
	when 'á'
		phrase_up[index] = 'á'
	when 'ã'
		phrase_up[index] = 'ã'
	when 'â'
		phrase_up[index] = 'â'
	when 'à'
		phrase_up[index] = 'à'
	when 'b'
		phrase_up[index] = 'b'
	when 'c'
		phrase_up[index] = 'c'
	when 'd'
		phrase_up[index] = 'd'
	when 'e'
		phrase_up[index] = 'e'
	when 'é'
		phrase_up[index] = 'é'
	when 'ê'
		phrase_up[index] = 'ê'
	when 'è'
		phrase_up[index] = 'è'
	when 'f'
		phrase_up[index] = 'f'
	when 'g'
		phrase_up[index] = 'g'
	when 'h'
		phrase_up[index] = 'h'
	when 'i'
		phrase_up[index] = 'i'
	when 'í'
		phrase_up[index] = 'í'
	when 'î'
		phrase_up[index] = 'î'
	when 'ì'
		phrase_up[index] = 'ì'
	when 'j'
		phrase_up[index] = 'j'
	when 'k'
		phrase_up[index] = 'k'
	when 'l'
		phrase_up[index] = 'l'
	when 'm'
		phrase_up[index] = 'm'
	when 'n'
		phrase_up[index] = 'n'
	when 'o'
		phrase_up[index] = 'o'
	when 'ó'
		phrase_up[index] = 'ó'
	when 'ô'
		phrase_up[index] = 'ô'
	when 'õ'
		phrase_up[index] = 'õ'
	when 'ò'
		phrase_up[index] = 'ò'
	when 'p'
		phrase_up[index] = 'p'
	when 'q'
		phrase_up[index] = 'q'
	when 'r'
		phrase_up[index] = 'r'
	when 's'
		phrase_up[index] = 's'
	when 't'
		phrase_up[index] = 't'
	when 'u'
		phrase_up[index] = 'u'
	when 'ú'
		phrase_up[index] = 'ú'
	when 'û'
		phrase_up[index] = 'û'
	when 'ù'
		phrase_up[index] = 'ù'
	when 'v'
		phrase_up[index] = 'v'
	when 'w'
		phrase_up[index] = 'w'
	when 'x'
		phrase_up[index] = 'x'
	when 'y'
		phrase_up[index] = 'y'
	when 'z'
		phrase_up[index] = 'z'
	when ' '
		phrase_up[index] = ' '
	end
	index += 1 
end

puts "#{phrase_up.join}"