puts "Digite uma frase: "
phrase = gets.chomp.split('')
phrase_up = []

phrase.each_with_index do |char, index|
	case char
	when 'a'
		phrase_up[index] = 'A'
	when 'á'
		phrase_up[index] = 'Á'
	when 'ã'
		phrase_up[index] = 'Ã'
	when 'â'
		phrase_up[index] = 'Â'
	when 'à'
		phrase_up[index] = 'À'
	when 'b'
		phrase_up[index] = 'B'
	when 'c'
		phrase_up[index] = 'C'
	when 'd'
		phrase_up[index] = 'D'
	when 'e'
		phrase_up[index] = 'E'
	when 'é'
		phrase_up[index] = 'É'
	when 'ê'
		phrase_up[index] = 'Ê'
	when 'è'
		phrase_up[index] = 'È'
	when 'f'
		phrase_up[index] = 'F'
	when 'g'
		phrase_up[index] = 'G'
	when 'h'
		phrase_up[index] = 'H'
	when 'i'
		phrase_up[index] = 'I'
	when 'í'
		phrase_up[index] = 'Í'
	when 'î'
		phrase_up[index] = 'Î'
	when 'ì'
		phrase_up[index] = 'ì'
	when 'j'
		phrase_up[index] = 'J'
	when 'k'
		phrase_up[index] = 'K'
	when 'l'
		phrase_up[index] = 'L'
	when 'm'
		phrase_up[index] = 'M'
	when 'n'
		phrase_up[index] = 'N'
	when 'o'
		phrase_up[index] = 'O'
	when 'ó'
		phrase_up[index] = 'Ó'
	when 'ô'
		phrase_up[index] = 'Ô'
	when 'õ'
		phrase_up[index] = 'Õ'
	when 'ò'
		phrase_up[index] = 'Ò'
	when 'p'
		phrase_up[index] = 'P'
	when 'q'
		phrase_up[index] = 'Q'
	when 'r'
		phrase_up[index] = 'R'
	when 's'
		phrase_up[index] = 'S'
	when 't'
		phrase_up[index] = 'T'
	when 'u'
		phrase_up[index] = 'U'
	when 'ú'
		phrase_up[index] = 'Ú'
	when 'û'
		phrase_up[index] = 'Û'
	when 'ù'
		phrase_up[index] = 'Ù'
	when 'v'
		phrase_up[index] = 'V'
	when 'w'
		phrase_up[index] = 'W'
	when 'x'
		phrase_up[index] = 'X'
	when 'y'
		phrase_up[index] = 'Y'
	when 'z'
		phrase_up[index] = 'Z'
	when ' '
		phrase_up[index] = ' '
	end
end

puts "#{phrase_up.join}"